name: Run tests

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - master
    paths:
      - '.github/workflows/tests.yml'
      - 'bun.lockb'
      - '**.ts'

env:
  HUSKY: 0

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        node-version: [18, 20, 22, 23]

    name: NodeJS ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v4
  
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Running tests
        run: bun test
